using System;
using IoC.InstallGenerator.Abstractions;

namespace Demo.Host
{
    public static partial class Program
    {        
        // T060: Implement Program.cs with IoCInstallerLoader usage
        static void Main(string[] args)
        {
            // Si se pasa "benchmark" como argumento, ejecutar el benchmark
            if (args.Length > 0 && args[0].Equals("benchmark", StringComparison.OrdinalIgnoreCase))
            {
                BenchmarkRunner.Run();
                return;
            }

            Console.WriteLine("IoC Install Generator Demo");
            Console.WriteLine("==========================");
            Console.WriteLine();

            try
            {
                // T059: Create container adapter
                var container = new SimpleContainerAdapter();

                // T060: Load all installers using generated code
                // The LoadAll method is generated by the source generator in the partial class
                Console.WriteLine("Loading installers...");
                Loader.LoadAll(container);
                Console.WriteLine("All installers loaded successfully!");
                Console.WriteLine();

                // Verify that services were registered
                Console.WriteLine("Verifying registered services...");
                Verifier.Verify(container);
            }
            catch (AggregateException ex)
            {
                Console.WriteLine("Error: One or more installers failed:");
                foreach (var innerEx in ex.InnerExceptions)
                {
                    Console.WriteLine($"  - {innerEx.Message}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}
